# Generated by Django 4.2.1 on 2023-12-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Pronouns',
            field=models.CharField(choices=[('He/Him', 'He/Him'), ('She/Her', 'She/Her'), ('They/Them', 'They/Them'), ('Other', 'Other')], max_length=20),
        ),
    ]
