# Generated by Django 4.2.1 on 2023-12-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='anonymous_from',
        ),
    ]
