# Generated by Django 4.2.1 on 2023-10-26 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profiles_alter_work_exp_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 26, 22, 6, 49, 131709)),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 26, 22, 6, 49, 131709)),
        ),
    ]
