# Generated by Django 4.2.1 on 2023-10-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_work_exp_alter_profiles_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Email',
            field=models.EmailField(default='vv@gmail.com', max_length=30),
        ),
    ]
