# Generated by Django 4.2.1 on 2023-10-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_work_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=100)),
                ('from_user', models.CharField(max_length=100)),
                ('aquaintance', models.CharField(choices=[('W', 'Work'), ('P', 'Personal'), ('O', 'Other')], default='H', max_length=1)),
                ('aquaintance_time', models.CharField(choices=[('L', 'Less than 1 year'), ('M', '1 to 3 years'), ('H', 'More than 3 years')], default='L', max_length=1)),
                ('relationship', models.CharField(choices=[('B', 'Boss'), ('E', 'Employee'), ('W', 'Colleague'), ('C', 'Client'), ('F', 'Friend'), ('R', 'Family or Relative'), ('O', 'Other')], default='B', max_length=1)),
                ('team_size', models.CharField(choices=[('L', 'Less than 5'), ('M', '5 to 20'), ('H', 'More than 20'), ('N', 'None')], default='N', max_length=1)),
                ('slider', models.IntegerField(default=0)),
                ('sentence', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='currently_working',
            field=models.BooleanField(default=1),
        ),
    ]
