# Generated by Django 4.2.1 on 2023-11-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_review_aquaintance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='slider',
            new_name='slider1',
        ),
        migrations.AddField(
            model_name='review',
            name='slider2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='slider3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='slider4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='slider5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='slider6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='slider7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='slider8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='slider9',
            field=models.IntegerField(default=0),
        ),
    ]
