# Generated by Django 4.2.1 on 2023-11-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_work_exp_currently_working'),
        ('main', '0010_rename_slider_review_slider1_review_slider2_and_more'),
    ]

    operations = [
    ]
