# Generated by Django 4.2.1 on 2023-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20231108_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
