# Generated by Django 4.2.1 on 2023-10-24 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='work_exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('emp_type', models.CharField(choices=[('F', 'Full-time'), ('P', 'Part-time')], default='F', max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('location_type', models.CharField(choices=[('O', 'Onsite'), ('H', 'Hybrid'), ('R', 'Remote')], default='O', max_length=30)),
                ('currently_working', models.BooleanField(default=True)),
                ('start_time', models.DateField(default=datetime.datetime(2023, 10, 24, 13, 3, 51, 6734))),
                ('end_time', models.DateField(default=datetime.datetime(2023, 10, 24, 13, 3, 51, 6752))),
            ],
        ),
    ]
