# Generated by Django 4.2.1 on 2023-09-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='people',
        ),
    ]
