# Generated by Django 4.2.5 on 2023-09-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbackend', '0002_rename_user_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('emp_type', models.CharField(choices=[('F', 'Full-time'), ('P', 'Part-time')], default='F', max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('location_type', models.CharField(choices=[('O', 'Onsite'), ('H', 'Hybrid'), ('R', 'Remote')], default='O', max_length=30)),
                ('currently_working', models.BooleanField(default=True)),
                ('start_time', models.DateField(default=None)),
                ('end_time', models.DateField(default=None)),
            ],
        ),
    ]
