# Generated by Django 4.2.5 on 2023-09-21 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbackend', '0005_alter_work_exp_end_time_alter_work_exp_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_exp',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djbackend.people'),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 1, 50, 2, 455213)),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 1, 50, 2, 455213)),
        ),
    ]
