# Generated by Django 4.2.5 on 2023-09-21 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbackend', '0008_alter_work_exp_end_time_alter_work_exp_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_exp',
            old_name='email',
            new_name='people',
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 1, 52, 40, 161498)),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 1, 52, 40, 161498)),
        ),
    ]
