# Generated by Django 4.2.5 on 2023-09-21 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbackend', '0012_alter_work_exp_end_time_alter_work_exp_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_exp',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 2, 3, 4, 116400)),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='people',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djbackend.people'),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 2, 3, 4, 116400)),
        ),
    ]
