# Generated by Django 4.2.1 on 2023-10-04 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbackend', '0021_alter_work_exp_end_time_alter_work_exp_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_exp',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 10, 18, 54, 729486)),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 4, 10, 18, 54, 729466)),
        ),
    ]
