# Generated by Django 4.2.1 on 2023-10-23 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbackend', '0023_alter_work_exp_end_time_alter_work_exp_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_exp',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 23, 0, 49, 32, 169386)),
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 23, 0, 49, 32, 169373)),
        ),
    ]
